version: "3"
services:
  limbo:
    build:
      context: .
    container_name: limbo
    restart: unless-stopped
    volumes:
      - ./server:/server
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    ports:
      - target: 29999
        published: 29999
        protocol: tcp
        mode: host
