version: "3"
services:
  limbo:
    build:
      context: .
    container_name: limbo
    restart: unless-stopped
    volumes:
      - ./server:/server
      - /etc/localtime:/etc/localtime:ro
    network_mode: host

